{{- if eq .Values.networkManager.config.enableLocalDiscovery true -}}
{{- $subnet := print .Values.networkManager.config.address.firstOctet "." .Values.networkManager.config.address.secondOctet "." .Values.networkManager.config.address.thirdOctet ".0/24" -}}
{{- $rangeStart := print .Values.networkManager.config.address.firstOctet "." .Values.networkManager.config.address.secondOctet "." .Values.networkManager.config.address.thirdOctet ".101" -}}
{{- $rangeEnd := print .Values.networkManager.config.address.firstOctet "." .Values.networkManager.config.address.secondOctet "." .Values.networkManager.config.address.thirdOctet ".101" -}}

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ (get .Values.networkManager.pod.annotations "k8s.v1.cni.cncf.io/networks" | split "@")._0 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "{{ .Values.networkManager.config.netInterface }}",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "{{ $subnet }}",
        "rangeStart": "{{ $rangeStart }}",
        "rangeEnd": "{{ $rangeEnd }}"
      }
    }'
{{- end }}