apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: control-plane-network-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: control-plane-network-manager
  template:
    metadata:
      labels:
        name: control-plane-network-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: network-manager
        image: {{ .Values.networkManager.imageName }}:0.0.1
        env:
        - name: CONTROL_PLANE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CLUSTER_ADDRESS
          value: "your-cluster-address"
        - name: MULTICAST_ADDRESS
          value: "224.0.0.155:4000"