//go:build !ignore_autogenerated

// Copyright 2022-2023 FLUIDOS Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Aggregatable) DeepCopyInto(out *Aggregatable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Aggregatable.
func (in *Aggregatable) DeepCopy() *Aggregatable {
	if in == nil {
		return nil
	}
	out := new(Aggregatable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allocation) DeepCopyInto(out *Allocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allocation.
func (in *Allocation) DeepCopy() *Allocation {
	if in == nil {
		return nil
	}
	out := new(Allocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Allocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationList) DeepCopyInto(out *AllocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Allocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationList.
func (in *AllocationList) DeepCopy() *AllocationList {
	if in == nil {
		return nil
	}
	out := new(AllocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AllocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationSpec) DeepCopyInto(out *AllocationSpec) {
	*out = *in
	out.Contract = in.Contract
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationSpec.
func (in *AllocationSpec) DeepCopy() *AllocationSpec {
	if in == nil {
		return nil
	}
	out := new(AllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationStatus) DeepCopyInto(out *AllocationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationStatus.
func (in *AllocationStatus) DeepCopy() *AllocationStatus {
	if in == nil {
		return nil
	}
	out := new(AllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Characteristics) DeepCopyInto(out *Characteristics) {
	*out = *in
	out.Cpu = in.Cpu.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.Pods = in.Pods.DeepCopy()
	out.Gpu = in.Gpu.DeepCopy()
	out.EphemeralStorage = in.EphemeralStorage.DeepCopy()
	out.PersistentStorage = in.PersistentStorage.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Characteristics.
func (in *Characteristics) DeepCopy() *Characteristics {
	if in == nil {
		return nil
	}
	out := new(Characteristics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flavour) DeepCopyInto(out *Flavour) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flavour.
func (in *Flavour) DeepCopy() *Flavour {
	if in == nil {
		return nil
	}
	out := new(Flavour)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Flavour) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavourList) DeepCopyInto(out *FlavourList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Flavour, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavourList.
func (in *FlavourList) DeepCopy() *FlavourList {
	if in == nil {
		return nil
	}
	out := new(FlavourList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlavourList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavourSelector) DeepCopyInto(out *FlavourSelector) {
	*out = *in
	if in.RangeSelector != nil {
		in, out := &in.RangeSelector, &out.RangeSelector
		*out = new(RangeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchSelector != nil {
		in, out := &in.MatchSelector, &out.MatchSelector
		*out = new(MatchSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavourSelector.
func (in *FlavourSelector) DeepCopy() *FlavourSelector {
	if in == nil {
		return nil
	}
	out := new(FlavourSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavourSpec) DeepCopyInto(out *FlavourSpec) {
	*out = *in
	in.Characteristics.DeepCopyInto(&out.Characteristics)
	in.Policy.DeepCopyInto(&out.Policy)
	out.Owner = in.Owner
	out.Price = in.Price
	out.OptionalFields = in.OptionalFields
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavourSpec.
func (in *FlavourSpec) DeepCopy() *FlavourSpec {
	if in == nil {
		return nil
	}
	out := new(FlavourSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavourStatus) DeepCopyInto(out *FlavourStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavourStatus.
func (in *FlavourStatus) DeepCopy() *FlavourStatus {
	if in == nil {
		return nil
	}
	out := new(FlavourStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRef) DeepCopyInto(out *GenericRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRef.
func (in *GenericRef) DeepCopy() *GenericRef {
	if in == nil {
		return nil
	}
	out := new(GenericRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoCredentials) DeepCopyInto(out *LiqoCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoCredentials.
func (in *LiqoCredentials) DeepCopy() *LiqoCredentials {
	if in == nil {
		return nil
	}
	out := new(LiqoCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchSelector) DeepCopyInto(out *MatchSelector) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.Pods = in.Pods.DeepCopy()
	out.Storage = in.Storage.DeepCopy()
	out.EphemeralStorage = in.EphemeralStorage.DeepCopy()
	out.Gpu = in.Gpu.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchSelector.
func (in *MatchSelector) DeepCopy() *MatchSelector {
	if in == nil {
		return nil
	}
	out := new(MatchSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIdentity) DeepCopyInto(out *NodeIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIdentity.
func (in *NodeIdentity) DeepCopy() *NodeIdentity {
	if in == nil {
		return nil
	}
	out := new(NodeIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionalFields) DeepCopyInto(out *OptionalFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionalFields.
func (in *OptionalFields) DeepCopy() *OptionalFields {
	if in == nil {
		return nil
	}
	out := new(OptionalFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Partition) DeepCopyInto(out *Partition) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.Pods = in.Pods.DeepCopy()
	out.Gpu = in.Gpu.DeepCopy()
	out.EphemeralStorage = in.EphemeralStorage.DeepCopy()
	out.Storage = in.Storage.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Partition.
func (in *Partition) DeepCopy() *Partition {
	if in == nil {
		return nil
	}
	out := new(Partition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Partitionable) DeepCopyInto(out *Partitionable) {
	*out = *in
	out.CpuMin = in.CpuMin.DeepCopy()
	out.MemoryMin = in.MemoryMin.DeepCopy()
	out.PodsMin = in.PodsMin.DeepCopy()
	out.CpuStep = in.CpuStep.DeepCopy()
	out.MemoryStep = in.MemoryStep.DeepCopy()
	out.PodsStep = in.PodsStep.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Partitionable.
func (in *Partitionable) DeepCopy() *Partitionable {
	if in == nil {
		return nil
	}
	out := new(Partitionable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseStatus) DeepCopyInto(out *PhaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseStatus.
func (in *PhaseStatus) DeepCopy() *PhaseStatus {
	if in == nil {
		return nil
	}
	out := new(PhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	if in.Partitionable != nil {
		in, out := &in.Partitionable, &out.Partitionable
		*out = new(Partitionable)
		(*in).DeepCopyInto(*out)
	}
	if in.Aggregatable != nil {
		in, out := &in.Aggregatable, &out.Aggregatable
		*out = new(Aggregatable)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Price) DeepCopyInto(out *Price) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Price.
func (in *Price) DeepCopy() *Price {
	if in == nil {
		return nil
	}
	out := new(Price)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeSelector) DeepCopyInto(out *RangeSelector) {
	*out = *in
	out.MinCpu = in.MinCpu.DeepCopy()
	out.MinMemory = in.MinMemory.DeepCopy()
	out.MinPods = in.MinPods.DeepCopy()
	out.MinEph = in.MinEph.DeepCopy()
	out.MinStorage = in.MinStorage.DeepCopy()
	out.MinGpu = in.MinGpu.DeepCopy()
	out.MaxCpu = in.MaxCpu.DeepCopy()
	out.MaxMemory = in.MaxMemory.DeepCopy()
	out.MaxPods = in.MaxPods.DeepCopy()
	out.MaxEph = in.MaxEph.DeepCopy()
	out.MaxStorage = in.MaxStorage.DeepCopy()
	out.MaxGpu = in.MaxGpu.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeSelector.
func (in *RangeSelector) DeepCopy() *RangeSelector {
	if in == nil {
		return nil
	}
	out := new(RangeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Solver) DeepCopyInto(out *Solver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Solver.
func (in *Solver) DeepCopy() *Solver {
	if in == nil {
		return nil
	}
	out := new(Solver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Solver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolverList) DeepCopyInto(out *SolverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Solver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolverList.
func (in *SolverList) DeepCopy() *SolverList {
	if in == nil {
		return nil
	}
	out := new(SolverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolverSpec) DeepCopyInto(out *SolverSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(FlavourSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolverSpec.
func (in *SolverSpec) DeepCopy() *SolverSpec {
	if in == nil {
		return nil
	}
	out := new(SolverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolverStatus) DeepCopyInto(out *SolverStatus) {
	*out = *in
	out.SolverPhase = in.SolverPhase
	out.Allocation = in.Allocation
	out.Contract = in.Contract
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolverStatus.
func (in *SolverStatus) DeepCopy() *SolverStatus {
	if in == nil {
		return nil
	}
	out := new(SolverStatus)
	in.DeepCopyInto(out)
	return out
}
