---
apiVersion: network.fluidos.eu/v1alpha1
kind: Broker
metadata:
  name: broker-sample
  namespace: fluidos
spec:
  name: broker-sample
  address: fluidos.top-ix.org
  # role
  # "publisher" -> publisher only, "subscriber" -> subscriber only
  # anything else -> both publisher AND subscriber
  role: both
  rule: "{\"MAXlatency\":1000,\"MINbandwidth\":1,\"locations\":[\"K\",\"J\",\"Z\"],\"example\":\"aAbB12\"}"
  metric: "{\"bandwidth\":1,\"latency\":10,\"location\":\"K\",\"foo\":\"bar\"}"
  #secrets must be created from certificates and key provided by broker server's administrator
  cacert: brokera-ca-xxxxx
  clcert: brokera-cl-yyyyy

